; MaoPaperang P2 Label V6 - PlatformIO configuration

[platformio]
default_envs = esp-wrover-kit

[env:esp32dev]
platform = espressif32 @3.2.0
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:esp-wrover-kit]
platform = espressif32 @3.2.0
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
